import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    _id : mongoose.Schema.Types.ObjectId, // this is the id automatically generated by the mongodb
    channelName : {
        type : String,
        required : true,
    },
    email : {
        type : String,
        required : true,
    },
    phone : {
        type : String,
        required : true,
    },
    password : {
        type : String,
        required : true,
    },
    logoUrl : {
        type : String,
        required : true,
    },
    logoId : {
        type : String,
        required : true,
    },
    subscribers : {
        type : Number,
        default : 0
    },
    subscribedChannels : [{type : mongoose.Schema.Types.ObjectId, ref : 'User'}] // here the user is the user collection
}, {timestamps : true});

export const User = mongoose.model('User', userSchema);
